Merge #1140
1140: [travis] publish branch builds, too r=ricab a=Saviq



Co-authored-by: Michał Sawicz <michal@sawicz.net>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,8 +6,25 @@ language: cpp
 git:
   depth: false
 
-if: |
+env:
+  global:
+  - SNAPCRAFT_ENABLE_ERROR_REPORTING=0
+  # regexes for release branch and tag
+  - MULTIPASS_RELEASE_BRANCH_PATTERN="^release/([0-9\.]+)$"
+  - MULTIPASS_RELEASE_TAG_PATTERN="^v([0-9]+\.[0-9]+)\.[0-9]+$"
+  # build label added to the version string
+  - MULTIPASS_BUILD_LABEL=""
+  # whether to publish the built packages
+  - MULTIPASS_PUBLISH=""
+  # which channel to publish to
+  - MULTIPASS_SNAP_CHANNEL=""
+  # options to pass to the build reporter
+  - MULTIPASS_REPORT_OPTIONS=()
+
+if: | # bors and release branches, release tags and all pull requests
   branch IN (staging, trying, master)
+  OR branch ~= env(MULTIPASS_RELEASE_BRANCH_PATTERN)
+  OR branch ~= env(MULTIPASS_RELEASE_TAG_PATTERN)
   OR type = pull_request
 
 addons:
@@ -17,16 +34,47 @@ addons:
     name: snapcraft
     classic: true
 
-env:
-  global:
-  - SNAPCRAFT_ENABLE_ERROR_REPORTING=0
-
 before_install:
 # determine build properties and targets
 - |
+  # tag all PR builds with their number
   if [ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]; then
-    export MULTIPASS_BUILD_LABEL="pr${TRAVIS_PULL_REQUEST}"
-    export MULTIPASS_SNAP_CHANNEL="edge/${MULTIPASS_BUILD_LABEL}"
+    MULTIPASS_BUILD_LABEL="pr${TRAVIS_PULL_REQUEST}"
+
+  # and all other non-branch builds with their Travis job number
+  elif [ "${TRAVIS_EVENT_TYPE}" != "push" ]; then
+    MULTIPASS_BUILD_LABEL="ci${TRAVIS_JOB_NUMBER}"
+  fi
+
+  # can't publish anything without credentials
+  if [ "${TRAVIS_SECURE_ENV_VARS}" == "true" ]; then
+
+    # when it's a release branch or tag
+    if [[ "${TRAVIS_BRANCH}" =~ ${MULTIPASS_RELEASE_BRANCH_PATTERN} \
+          || "${TRAVIS_BRANCH}" =~ ${MULTIPASS_RELEASE_TAG_PATTERN} ]]; then
+
+      # publish pushes on beta/*
+      if [ "${TRAVIS_EVENT_TYPE}" == "push" ]; then
+        MULTIPASS_PUBLISH="true"
+        MULTIPASS_SNAP_CHANNEL="beta/${BASH_REMATCH[1]}"
+      fi
+
+      # but report on the PR if it's a release branch
+      if [[ "${TRAVIS_BRANCH}" == release/* ]]; then
+        MULTIPASS_REPORT_OPTIONS+=("--branch" "${TRAVIS_BRANCH}")
+      fi
+
+    # other branches only publish on the commits
+    # skip staging as the same commit will be published from master if all is good
+    elif [[ "${TRAVIS_EVENT_TYPE}" == "push" \
+            && "${TRAVIS_BRANCH}" != "staging" ]]; then
+      MULTIPASS_PUBLISH="true"
+
+    # non-release publish on edge/pr*
+    elif [ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]; then
+      MULTIPASS_PUBLISH="true"
+      MULTIPASS_SNAP_CHANNEL="edge/${MULTIPASS_BUILD_LABEL}"
+    fi
   fi
 
 # extract credentials
@@ -36,6 +84,10 @@ before_install:
       -in tools/bot-data.tar.xz.enc -out tools/bot-data.tar.xz -d
     tar --extract --xz --file tools/bot-data.tar.xz --directory ${HOME}
   fi
+
+# install tooling requiements
+- pyenv local 3.7.1
+- python3 -m pip install --requirement tools/requirements.txt
 
 install:
 - sudo apt remove --purge --assume-yes lxd lxd-client
@@ -77,7 +129,6 @@ jobs:
       - sg lxd -c '/snap/bin/snapcraft --use-lxd'
       - SNAP_ENFORCE_RESQUASHFS=0 /snap/bin/review-tools.snap-review --allow-classic *.snap
       after_success:
-      - '[[ "${TRAVIS_EVENT_TYPE}" != "pull_request" || "${TRAVIS_SECURE_ENV_VARS}" == "false" ]] && exit'
       - BUILDS=()
       - >-
         [ -n "${MULTIPASS_SNAP_CHANNEL}" ]
@@ -85,9 +136,12 @@ jobs:
         && snapcraft push multipass_*.snap --release ${MULTIPASS_SNAP_CHANNEL}
         && BUILDS+=("\`snap refresh multipass --channel ${MULTIPASS_SNAP_CHANNEL}\`")
       - CURL_OUTPUT=$( timeout 5m curl --fail --upload-file *.snap https://transfer.sh/ )
+        || ( echo "Upload failed..."; false )
         && BUILDS+=("[$( basename ${CURL_OUTPUT} )](${CURL_OUTPUT})");
         echo ${CURL_OUTPUT}
-      - ./tools/report_build.py Snap "${BUILDS[@]}"
+      - >-
+        [ -n "${MULTIPASS_PUBLISH}" ]
+        && python3 -m tools.report_build "${MULTIPASS_REPORT_OPTIONS[@]}" Snap "${BUILDS[@]}"
 
     - env: BUILD_TYPE=Clang
       before_script: *before_snapcraft
@@ -141,9 +195,10 @@ jobs:
         ssh -q -p ${MAC_PORT} ${MAC_USERHOST} multipass-build/build-in-snapshot.sh public "${REF}" "${ARTIFACTS_DIR}" "${MULTIPASS_BUILD_LABEL}"
         scp -P ${MAC_PORT} ${MAC_USERHOST}:${ARTIFACTS_DIR}/*.pkg .
       after_success:
-      - '[ "${TRAVIS_EVENT_TYPE}" != "pull_request" ] && exit'
       - CURL_OUTPUT=$( timeout 5m curl --fail --upload-file *.pkg https://transfer.sh/ )
-        && ./tools/report_build.py macOS "[$( basename ${CURL_OUTPUT} )](${CURL_OUTPUT})";
+        || ( echo "Upload failed..."; false )
+        && [ -n "${MULTIPASS_PUBLISH}" ]
+        && python3 -m tools.report_build "${MULTIPASS_REPORT_OPTIONS[@]}" macOS "[$( basename ${CURL_OUTPUT} )](${CURL_OUTPUT})";
         echo ${CURL_OUTPUT}
       after_script: ~
       after_failure: ~
