check_kvm_support: Add support for other CPU types

diff --git a/src/platform/backends/qemu/check_kvm_support b/src/platform/backends/qemu/check_kvm_support
--- a/src/platform/backends/qemu/check_kvm_support
+++ b/src/platform/backends/qemu/check_kvm_support
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright © 2017 Canonical Ltd.
+# Copyright © 2017-2019 Canonical Ltd.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License version 3 as
@@ -24,9 +24,32 @@ check_kvm_module() {
 
 check_kvm_module
 
-virt=$(egrep -m1 -w '^flags[[:blank:]]*:' /proc/cpuinfo | egrep -wo '(vmx|svm)') || true
-[ "$virt" = "vmx" ] && kvm_mod="kvm_intel"
-[ "$virt" = "svm" ] && kvm_mod="kvm_amd"
+ARM_CPU_PART_CORTEX_A15="0xc0f" # <asm/cputype.h>
+
+# check cpu flags for capability
+case "$(uname -m)" in
+    armv7l)
+        if egrep -m1 -w '^CPU part[[:blank:]]*:' /proc/cpuinfo | \
+                egrep -wq "$ARM_CPU_PART_CORTEX_A15"; then
+            virt="ARM"
+            kvm_mod="kvm"
+        fi
+        ;;
+    aarch64)
+        virt="ARM"
+        kvm_mod="kvm"
+        ;;
+    ppc64le|ppc64|s390x)
+        # FIXME: Assume that all POWER and z/Systems are KVM capable
+        virt="generic"
+        kvm_mod="kvm"
+        ;;
+    *)
+        virt=$(egrep -m1 -w '^flags[[:blank:]]*:' /proc/cpuinfo | egrep -wo '(vmx|svm)') || true
+        [ "$virt" = "vmx" ] && kvm_mod="kvm_intel"
+        [ "$virt" = "svm" ] && kvm_mod="kvm_amd"
+        ;;
+esac
 
 if [ -z "$virt" ]; then
     echo "CPU does not support KVM extensions."
@@ -68,5 +91,5 @@ modprobe $kvm_mod
 
 check_kvm_module
 
-echo "Unable to load '$kvm_mod'."
+echo "Unable to load kvm support. Please ensure kvm is installed on your machine."
 exit 1
