check_kvm_support: Use better error message when msr module fails loading
Fixes #811

diff --git a/src/platform/backends/qemu/check_kvm_support b/src/platform/backends/qemu/check_kvm_support
--- a/src/platform/backends/qemu/check_kvm_support
+++ b/src/platform/backends/qemu/check_kvm_support
@@ -62,7 +62,9 @@ if [ "$(id -u)" != "0" ]; then
 else
     msr="/dev/cpu/0/msr"
     if [ ! -r "$msr" ]; then
-        modprobe msr
+        if ! modprobe msr > /dev/null 2>&1 ; then
+            echo "Cannot check BIOS for determining KVM extensions support."
+        fi
     fi
 
     if [ "$virt" = "vmx" ]; then
