[ci] Customize check of missing newline at EOF
Replace an external action to check for missing newlines at EOF, in
order to afford exclusions for vendored code (exclusions to be
implemented).

diff --git a/.github/actions/whitespace/action.yml b/.github/actions/whitespace/action.yml
--- a/.github/actions/whitespace/action.yml
+++ b/.github/actions/whitespace/action.yml
@@ -14,3 +14,14 @@ runs:
           ':(exclude)3rd-party/'     `# third-party submodules` \
           ':(exclude)data/'          `# data files`             \
           ':(exclude)docs/.sphinx/'  `# vendored`
+
+    - name: Check for missing newline at EOF
+      shell: bash
+      run: |
+        set -e -o pipefail
+
+        git grep --no-color -Ilz '' | xargs -0 grep -lzP '(?:[^\n]|\n\n)\z'
+        if [ $? -eq 0 ]; then
+          echo "##[error] Files above end with multiple or no newline at all"
+          exit 1
+        fi
