force docs failure

diff --git a/.github/workflows/automatic-doc-checks.yml b/.github/workflows/automatic-doc-checks.yml
--- a/.github/workflows/automatic-doc-checks.yml
+++ b/.github/workflows/automatic-doc-checks.yml
@@ -12,7 +12,9 @@ concurrency:
 
 jobs:
   documentation-checks:
-    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
-    with:
-      working-directory: "./docs"
-      fetch-depth: 0
+    runs-on: ubuntu-latest
+    steps:
+      - name: “Intentionally fail for testing”
+        run: |
+          echo "🚨 Forcing failure (docs workflow) for testing purposes"
+          exit 1
