[cli-tests] Use the right kind of reporter
Signed-off-by: Mustafa Kemal Gilor <mustafa.gilor@canonical.com>

diff --git a/.github/workflows/cli-tests.yml b/.github/workflows/cli-tests.yml
--- a/.github/workflows/cli-tests.yml
+++ b/.github/workflows/cli-tests.yml
@@ -35,13 +35,13 @@ jobs:
 
       - name: Run cli-tests
         id: run-cli-tests
-        run: pytest -s tools/cli_tests --remove-all-instances --daemon-controller=snap --junitxml=reports/junit.xml
+        run: pytest -s tools/cli_tests --remove-all-instances --daemon-controller=snap --junitxml=reports/junit.xml -m authenticate
 
       - name: Report cli-tests results to Github Checks
-        if: always()
-        uses: dorny/test-reporter@v1
+        if: success() || failure()
+        uses: dorny/test-reporter@v2
         with:
           name: CLI Test results (Ubuntu 24.04)
           path: reports/junit.xml
-          reporter: jest-junit   # understands standard JUnit
-          fail-on-error: true    # fail job if there are test failures
+          reporter: java-junit # understands standard JUnit
+          fail-on-error: true # fail job if there are test failures
