[windows-macos] Macos: remove the arch wrapper
The arch wrapper is needed when cross-compiling, i.e. intel->arm and
vice versa. The reason why the arch wrapper was needed in the beginning
was there were no ARM based runners as described in this commit:

> https://github.com/canonical/multipass/commit/bbe964b893df660ca52f2a7acf68914405068c2f

Since then, the arch wrapper has basically became redundant. We now use
the respective arch for producing intel and arm packages, hence making
the wrapper redundant.

Made several changes on the steps that depend on the "arch" variable:

- Replaced the arch check in nuget shim replace step with a file type
check.
- Install nuget step now checks if nuget or mono is present or not. If
not, then proceeds with installing them.

Signed-off-by: Mustafa Kemal Gilor <mustafa.gilor@canonical.com>

diff --git a/.github/workflows/windows-macos.yml b/.github/workflows/windows-macos.yml
--- a/.github/workflows/windows-macos.yml
+++ b/.github/workflows/windows-macos.yml
@@ -35,9 +35,9 @@ jobs:
 
         MATRIX='{"include": ['
         MATRIX+='{"runs-on": "windows-latest"},'
-        MATRIX+='{"runs-on": "macos-13", "arch": "x86_64", "mono": "mono"},'
-        MATRIX+='{"runs-on": "macos-14", "arch": "arm64"},'
-        MATRIX+='{"runs-on": "macos-latest", "arch": "arm64"}'
+        MATRIX+='{"runs-on": "macos-13", "mono": "mono"},'
+        MATRIX+='{"runs-on": "macos-14" },'
+        MATRIX+='{"runs-on": "macos-latest"}'
         MATRIX+=']}'
 
         echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT
@@ -105,10 +105,6 @@ jobs:
         # Needed for cache: https://github.com/actions/cache?tab=readme-ov-file#pre-requisites
         echo "$( brew --prefix gnu-tar )/libexec/gnubin" >> ${GITHUB_PATH}
 
-    - name: Set the arch wrapper
-      if: ${{ matrix.arch }}
-      run: echo "ARCH_WRAPPER=arch -arch ${{ matrix.arch }}" >> ${GITHUB_ENV}
-
       # TODO: find a friendlier approach for installing pip packages on GitHub runners
     - name: Force pip to allow break-system-packages via pip.conf
       if: ${{ runner.os == 'macOS' }}
@@ -120,10 +116,8 @@ jobs:
       if: ${{ runner.os == 'macOS' }}
       run: |
         # Avoid reinstalling cmake
-        ${{ env.ARCH_WRAPPER }} brew list cmake > /dev/null || \
-            ${{ env.ARCH_WRAPPER }} brew install cmake
+        brew list cmake > /dev/null || brew install cmake
 
-        ${{ env.ARCH_WRAPPER }} \
         brew install \
           coreutils \
           dylibbundler \
@@ -142,7 +136,7 @@ jobs:
     - name: Install dependencies from pip
       if: ${{ runner.os == 'macOS' }}
       run: |
-        ${ARCH_WRAPPER} python3 -m pip install --user --upgrade distlib
+        python3 -m pip install --user --upgrade distlib
 
     - name: Install specific QEMU from Choco
       if: ${{ runner.os == 'Windows' }}
@@ -171,10 +165,15 @@ jobs:
           echo "VCPKG_BINARY_SOURCES=" >> $GITHUB_ENV
         fi
 
-    - name: Install nuget
-      if: ${{ matrix.arch == 'arm64' }}
+    - name: Install 'nuget' and 'mono' if missing 
+      if: ${{ runner.os == 'macOS' }}
       run: |
-        brew install nuget mono
+          for pkg in nuget mono; do
+            if ! command -v $pkg >/dev/null 2>&1; then
+              echo "$pkg not found, installing..."
+              brew install $pkg
+            fi
+          done
 
     - name: Configure NuGet Source
       if: ${{ env.VCPKG_BINARY_SOURCES }} # TODO: remove this when self-hosted runners are dropped
@@ -196,20 +195,23 @@ jobs:
 
     - name: Overwrite Homebrew nuget shim with nuget DLL
       continue-on-error: true
-      if: ${{ steps.setup_nuget.outcome == 'success' && runner.os == 'macOS' && matrix.arch == 'arm64' }}
+      if: ${{ steps.setup_nuget.outcome == 'success' && runner.os == 'macOS' }}
       run: |
         # Locate the real NuGet.exe in Homebrew’s Cellar
         NUGET_EXE="$(brew --prefix nuget)/libexec/NuGet.exe"
-        # Remove the old shim and replace it with a symlink
-        sudo rm -f /opt/homebrew/bin/nuget
-        sudo ln -s "$NUGET_EXE" /opt/homebrew/bin/nuget
-        sudo chmod +x /opt/homebrew/bin/nuget
+        if file "$NUGET_EXE" | grep -q "text"; then
+          # Remove the old shim and replace it with a symlink
+          echo "$NUGET_EXE is a shim, replacing"
+          sudo rm -f /opt/homebrew/bin/nuget
+          sudo ln -s "$NUGET_EXE" /opt/homebrew/bin/nuget
+          sudo chmod +x /opt/homebrew/bin/nuget
+        fi
 
     - name: Set up CCache
       if: ${{ runner.os == 'macOS' }}
       id: setup-ccache
       run: |
-        ${{ env.ARCH_WRAPPER }} brew install ccache
+        brew install ccache
 
         # Find common base between main and HEAD to use as cache key.
         # This avoids PRs from publishing caches.
@@ -257,7 +259,6 @@ jobs:
 
     - name: Configure
       run: >
-        ${{ env.ARCH_WRAPPER }}
         cmake
         -B${{ env.BUILD_DIR }}
         -DCMAKE_BUILD_TYPE=RelWithDebInfo
@@ -269,7 +270,7 @@ jobs:
         ${{ github.workspace }}
 
     - name: Build
-      run: ${{ env.ARCH_WRAPPER }} cmake --build ${{ env.BUILD_DIR }}
+      run: cmake --build ${{ env.BUILD_DIR }}
 
     - name: Clear CCache stats
       if: ${{ runner.os == 'macOS' }}
@@ -278,13 +279,13 @@ jobs:
     - name: Test
       working-directory: ${{ env.BUILD_DIR }}
       run: |
-        ${{ env.ARCH_WRAPPER }} bin/multipass_tests
+        bin/multipass_tests
 
     - name: Package
       id: cmake-package
       working-directory: ${{ env.BUILD_DIR }}
       run: >
-        ${{ env.ARCH_WRAPPER }} cmake --build . --target package
+        cmake --build . --target package
 
         echo "name=$( ${{ runner.os != 'Windows' && 'basename *.pkg' ||
         '( Get-ChildItem .\packages\en-US\multipass-*.msi ).Name' }} ) " >>
@@ -332,8 +333,8 @@ jobs:
       shell: bash
       run: |
         NAME="${{ steps.cmake-package.outputs.name }}"
-        ARTIFACT_NAME="${{ matrix.runs-on }}-${{ matrix.arch }}-package-artifact-name=${{ matrix.runs-on }}-${NAME}"
-        FILE_NAME="${{ matrix.runs-on }}-${{ matrix.arch }}-package-file-name=${NAME}"
+        ARTIFACT_NAME="${{ matrix.runs-on }}-package-artifact-name=${{ matrix.runs-on }}-${NAME}"
+        FILE_NAME="${{ matrix.runs-on }}-package-file-name=${NAME}"
 
         echo "$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"
         echo "$FILE_NAME" >> "$GITHUB_OUTPUT"
@@ -371,27 +372,22 @@ jobs:
       with:
         name: ${{ needs.BuildAndTest.outputs.mac-arm-package-artifact-name }}
 
-    - name: Set the arch wrapper
-      run: >
-        echo "ARCH_WRAPPER=arch -arch $( sysctl machdep.cpu.brand_string | grep -q Apple &&
-          echo arm64 || echo x86_64 )" >> ${GITHUB_ENV}
-
     - name: Combine the macOS package
       id: combine-package
       if: ${{ steps.retrieve-x86.outputs.download-path && steps.retrieve-arm.outputs.download-path }}
       run: |
-        ${ARCH_WRAPPER} brew install python
-        ${ARCH_WRAPPER} brew install coreutils
-        ${ARCH_WRAPPER} python3 -m pip install --user --upgrade lxml
+        brew install python
+        brew install coreutils
+        python3 -m pip install --user --upgrade lxml
 
         PKG=${{ needs.BuildAndTest.outputs.mac-x86-package-file-name }}
         PKG=${PKG/.x86_64/}
-        ${ARCH_WRAPPER} packaging/macos/merge_pkgs.py \
+        packaging/macos/merge_pkgs.py \
           ${{ needs.BuildAndTest.outputs.mac-x86-package-file-name }} \
           ${{ needs.BuildAndTest.outputs.mac-arm-package-file-name }} \
           ${PKG}
 
-        ${ARCH_WRAPPER} packaging/macos/sign-and-notarize.sh \
+        packaging/macos/sign-and-notarize.sh \
           --app-signer - \
           ${PKG}
 
